name: Deploy Workers

on:
  push:
    branches: [main]

jobs:
  deploy-notification:
    if: contains(github.event.head_commit.message, 'notification')
    environment: Cloudflare # Github Enviroment
    runs-on: ubuntu-latest
    env:
      WORKER_NAME: notification
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }} # Enviroment 中定义的 secrets

    steps:
      # - run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - run: echo "running  ${{ github.job }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm install -g wrangler

      # Set Cloudflare vars  # Enviroment 中定义的 secrets 和 variables 都用 ${{ secrets.xx }}
      - name: Set Cloudflare secrets
        run: |
          echo "${{ secrets.NOTIFICATION_WX_APPID }}"       | wrangler --name $WORKER_NAME secret put WX_TEMPLATE_ID
          echo "${{ secrets.NOTIFICATION_WX_SECRET }}"      | wrangler --name $WORKER_NAME secret put WX_TEMPLATE_ID
          echo "${{ secrets.NOTIFICATION_WX_USERID }}"      | wrangler --name $WORKER_NAME secret put WX_TEMPLATE_ID
          echo "${{ secrets.NOTIFICATION_API_TOKEN }}"      | wrangler --name $WORKER_NAME secret put API_TOKEN
          echo "${{ secrets.NOTIFICATION_WX_BASE_URL }}"    | wrangler --name $WORKER_NAME secret put WX_BASE_URL
          echo "${{ secrets.NOTIFICATION_WX_TEMPLATE_ID }}" | wrangler --name $WORKER_NAME secret put WX_TEMPLATE_ID
      
      - name: Deploy worker
        run: wrangler deploy
        working-directory: workers/notification